[2025-01-21T14:50:28.576+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 04_task_sequence_morning.exit manual__2025-01-21T14:50:06.826875+00:00 [queued]>
[2025-01-21T14:50:28.596+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 04_task_sequence_morning.exit manual__2025-01-21T14:50:06.826875+00:00 [queued]>
[2025-01-21T14:50:28.597+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-01-21T14:50:28.632+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): exit> on 2025-01-21 14:50:06.826875+00:00
[2025-01-21T14:50:28.641+0000] {standard_task_runner.py:60} INFO - Started process 713 to run task
[2025-01-21T14:50:28.645+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '04_task_sequence_morning', 'exit', 'manual__2025-01-21T14:50:06.826875+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/04_task_sequence_dag.py', '--cfg-path', '/tmp/tmppambfhv7']
[2025-01-21T14:50:28.653+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask exit
[2025-01-21T14:50:28.697+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-01-21T14:50:28.782+0000] {task_command.py:423} INFO - Running <TaskInstance: 04_task_sequence_morning.exit manual__2025-01-21T14:50:06.826875+00:00 [running]> on host d3a2c9f62df6
[2025-01-21T14:50:28.965+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='04_task_sequence_morning' AIRFLOW_CTX_TASK_ID='exit' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T14:50:06.826875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T14:50:06.826875+00:00'
[2025-01-21T14:50:28.968+0000] {logging_mixin.py:188} INFO - Take out
[2025-01-21T14:50:28.972+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-21T14:50:28.987+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=04_task_sequence_morning, task_id=exit, execution_date=20250121T145006, start_date=20250121T145028, end_date=20250121T145028
[2025-01-21T14:50:29.066+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-21T14:50:29.110+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
